In [1]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

# 6.5.1. Layers without Parameters

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [3]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

d:\_Software\miniconda3\envs\d2l\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(3.7253e-09, grad_fn=<MeanBackward0>)

# 6.5.2. Layers with Parameters

In [8]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight) + self.bias
        return F.relu(linear)

In [9]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.0917, -0.6781,  1.4030],
        [-1.0108, -0.6944, -0.5281],
        [ 0.1272, -0.3748, -1.7663],
        [ 0.8421, -0.1458, -2.0350],
        [-0.9176,  0.8903, -0.0662]], requires_grad=True)

In [10]:
linear(torch.rand(2, 5))

tensor([[0.0000, 1.0355, 0.0000],
        [0.0000, 0.9822, 0.0000]], grad_fn=<ReluBackward0>)

In [11]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[7.8606],
        [7.9601]], grad_fn=<ReluBackward0>)