In [1]:
import torch
from torch import nn

In [2]:
net = nn.Sequential(
    nn.LazyLinear(8),
    nn.ReLU(),
    nn.LazyLinear(1)
)

X = torch.rand(size=(2, 4))
net(X).shape

d:\_Software\miniconda3\envs\d2l\lib\site-packages\torch\nn\modules\lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([2, 1])

# 6.2.1. Parameter Access

In [3]:
net[2].state_dict()

OrderedDict([('weight',
              tensor([[ 0.2306,  0.1237, -0.3504, -0.2804, -0.3285,  0.0228,  0.0884, -0.2550]])),
             ('bias', tensor([0.0774]))])

# 6.2.1.1. Targeted Parameters

In [4]:
type(net[2].bias), net[2].bias.data

(torch.nn.parameter.Parameter, tensor([0.0774]))

In [5]:
net[2].weight.grad == None

True

# 6.2.1.2. All Parameters at Once

In [6]:
[(name, param.shape) for name, param in net.named_parameters()]

[('0.weight', torch.Size([8, 4])),
 ('0.bias', torch.Size([8])),
 ('2.weight', torch.Size([1, 8])),
 ('2.bias', torch.Size([1]))]

# 6.2.2. Tied Parameters

In [ ]:
# We need to give the shared layer a name so that we can refer to its parameters.
shared = nn.LazyLinear(8)
net = nn.Sequential(
    nn.LazyLinear(8), nn.ReLU(),
    shared, nn.ReLU(),
    shared, nn.ReLU(),
    nn.LazyLinear(1)
)
net(X)

# Check whether the parameters are the same
print(net[2].weight.data[0] == net[4].weight.data[0])

# Make sure that they are actually the same object rather than just having the same value.
net[2].weight.data[0, 0] = 100  # If they are the same object, this will change both.
print(net[2].weight.data[0] == net[4].weight.data[0])

tensor([True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True])
